import type { Metadata } from "next";
import { notFound } from "next/navigation";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import { Navbar } from "@/components/site/navbar";
import { Footer } from "@/components/site/footer";
import { ReadingProgress } from "@/components/site/reading-progress";
import { BackToTop } from "@/components/site/back-to-top";
import { ShareButtons } from "@/components/site/share-buttons";
import { HeadingAnchor } from "@/components/site/heading-anchor";
import { withBase } from "@/lib/paths";
import {
  TableOfContents,
} from "@/components/site/table-of-contents";
import {
  ArticleBackLink,
  ArticleTitle,
  ArticleMeta,
  ArticleTags,
  RelatedPosts,
  PostNav,
  ArticleFooterNote,
} from "@/components/site/blog-article-chrome";
import { CodeBlock } from "@/components/site/code-block";
import { headingId, type TocHeading } from "@/lib/toc";
import { shortHash } from "@/lib/utils";
import { blogPosts, getPostBySlug } from "@/lib/site-data";

/** Raw fenced-code language id (the CodeBlock resolves its localized label). */
function codeLangRaw(children: React.ReactNode): string | null {
  const child = (Array.isArray(children) ? children[0] : children) as
    | { props?: { className?: string } }
    | undefined;
  const className = child?.props?.className ?? "";
  return /language-([\w-]+)/.exec(className)?.[1] ?? null;
}

/** Extract h2/h3 headings from markdown source for the TOC. */
function extractHeadings(content: string): TocHeading[] {
  const headings: TocHeading[] = [];
  let index = 0;
  for (const line of content.split("\n")) {
    const match = line.match(/^(#{2,3})\s+(.+)$/);
    if (!match) continue;
    const level = match[1].length === 2 ? 2 : 3;
    const text = match[2]
      .replace(/[`*_~]/g, "")
      .trim();
    headings.push({ id: headingId(text, index), text, level });
    index += 1;
  }
  return headings;
}

/**
 * Estimate the word count of each TOC section (heading → next heading).
 * Intro words before the first heading are attributed to the first section;
 * fenced code blocks are skipped so diagrams don't inflate the estimate.
 */
function sectionWordCounts(content: string, headings: TocHeading[]): number[] {
  const counts = headings.map(() => 0);
  if (headings.length === 0) return counts;
  let current = 0;
  let idx = -1;
  let intro = 0;
  let inFence = false;
  for (const line of content.split("\n")) {
    if (/^`{3,}/.test(line.trim())) inFence = !inFence;
    if (!inFence && /^(#{2,3})\s+/.test(line)) {
      if (idx >= 0) counts[idx] = current;
      idx += 1;
      current = 0;
      continue;
    }
    const words = line.split(/\s+/).filter(Boolean).length;
    if (idx === -1) intro += words;
    else current += words;
  }
  if (idx >= 0) counts[idx] = current;
  counts[0] += intro;
  return counts;
}

/** Flatten ReactMarkdown children to plain text for id computation. */
function childText(children: React.ReactNode): string {
  if (Array.isArray(children)) return children.map(String).join("");
  return String(children);
}

/** Only slugs from generateStaticParams are valid — unknown slugs 404 at the
 *  routing level (avoids the loading.tsx streaming shell answering 200). */
export const dynamicParams = false;

export function generateStaticParams() {
  return blogPosts.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) return { title: "نوشته پیدا نشد" };

  /* Per-article social preview generated by /api/og (Dana font, site theme). */
  const faDate = new Intl.DateTimeFormat("fa-IR", {
    dateStyle: "long",
  }).format(new Date(post.dateISO));
  const ogImage = `/api/og?${new URLSearchParams({
    title: post.title,
    chip: post.category,
    date: faDate,
    /* Content-hash key: social previews refresh as soon as the post changes. */
    v: shortHash(`${post.title}|${post.category}|${post.dateISO}`),
  }).toString()}`;

  return {
    title: `${post.title} — بلاگ امیرعلی طاهری`,
    description: post.excerpt,
    openGraph: {
      title: post.title,
      description: post.excerpt,
      type: "article",
      publishedTime: post.dateISO,
      authors: ["امیرعلی طاهری"],
      tags: post.tags,
      images: [{ url: withBase(ogImage), alt: post.title }],
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.excerpt,
      images: [withBase(ogImage)],
    },
  };
}

export default async function BlogArticlePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) notFound();

  const headings = extractHeadings(post.content);
  const sectionWords = sectionWordCounts(post.content, headings);
  let headingIndex = 0;
  const nextHeadingId = (text: string) => headingId(text, headingIndex++);

  return (
    <>
      <ReadingProgress />
      <BackToTop />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "BlogPosting",
            headline: post.title,
            description: post.excerpt,
            datePublished: post.dateISO,
            inLanguage: "fa",
            articleSection: post.category,
            keywords: post.tags.join(", "),
            author: {
              "@type": "Person",
              name: "امیرعلی طاهری",
              email: "azazamir139@gmail.com",
            },
          }),
        }}
      />
      <Navbar />
      <main id="main-content" className="grow">
        <article className="mx-auto max-w-3xl px-3 pt-28 pb-8 sm:px-4 md:px-8 md:pt-36 md:pb-16">
          <ArticleBackLink />

          <header className="mt-6 flex flex-col gap-4">
            <ArticleTitle slug={post.slug} />
            <ArticleMeta slug={post.slug} />
            <ArticleTags slug={post.slug} />
            <ShareButtons title={post.title} />
            <div className="h-px bg-border/60" />
          </header>

          <TableOfContents headings={headings} sectionWords={sectionWords} />

          <div className="mt-8 flex flex-col gap-1 text-base leading-8 text-foreground/90">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                h2: ({ children }) => {
                  const text = childText(children);
                  const id = nextHeadingId(text);
                  return (
                    <h2
                      id={id}
                      className="group mt-10 mb-4 scroll-mt-28 text-2xl font-semibold tracking-tight text-foreground"
                    >
                      {children}
                      <HeadingAnchor id={id} label={text} />
                    </h2>
                  );
                },
                h3: ({ children }) => {
                  const text = childText(children);
                  const id = nextHeadingId(text);
                  return (
                    <h3
                      id={id}
                      className="group mt-8 mb-3 scroll-mt-28 text-xl font-semibold tracking-tight text-foreground"
                    >
                      {children}
                      <HeadingAnchor id={id} label={text} />
                    </h3>
                  );
                },
                p: ({ children }) => (
                  <p className="text-justify leading-8 mb-4">{children}</p>
                ),
                ul: ({ children }) => (
                  <ul className="list-disc space-y-2 ps-6 mb-4 marker:text-primary">
                    {children}
                  </ul>
                ),
                ol: ({ children }) => (
                  <ol className="list-decimal space-y-2 ps-6 mb-4 marker:text-primary">
                    {children}
                  </ol>
                ),
                blockquote: ({ children }) => (
                  <blockquote className="my-6 rounded-lg border-s-4 border-primary/60 bg-primary/5 px-5 py-3 text-muted-foreground">
                    {children}
                  </blockquote>
                ),
                a: ({ href, children }) => (
                  <a
                    href={href}
                    className="text-primary hover:underline font-medium"
                    target="_blank"
                    rel="noreferrer"
                  >
                    {children}
                  </a>
                ),
                code: ({ children, className }) => {
                  const isBlock = Boolean(className);
                  if (isBlock) {
                    return (
                      <code
                        className="block text-sm leading-7 text-left font-medium"
                        dir="ltr"
                      >
                        {children}
                      </code>
                    );
                  }
                  return (
                    <code
                      className="rounded bg-muted px-1.5 py-0.5 text-sm font-medium text-foreground"
                      dir="ltr"
                    >
                      {children}
                    </code>
                  );
                },
                pre: ({ children }) => (
                  <CodeBlock lang={codeLangRaw(children)}>
                    <pre
                      className="my-6 overflow-x-auto rounded-lg border border-border/60 bg-card p-4 text-sm"
                      dir="ltr"
                    >
                      {children}
                    </pre>
                  </CodeBlock>
                ),
                strong: ({ children }) => (
                  <strong className="font-semibold text-foreground">{children}</strong>
                ),
                table: ({ children }) => (
                  <div className="my-6 overflow-x-auto rounded-lg border border-border/60 bg-card">
                    <table className="w-full border-collapse text-sm">{children}</table>
                  </div>
                ),
                thead: ({ children }) => (
                  <thead className="bg-muted/60 text-foreground">{children}</thead>
                ),
                th: ({ children }) => (
                  <th className="border-b border-border/60 px-4 py-2.5 text-start font-semibold whitespace-nowrap">
                    {children}
                  </th>
                ),
                td: ({ children }) => (
                  <td className="border-b border-border/40 px-4 py-2.5 align-top last:border-b-0">
                    {children}
                  </td>
                ),
                tr: ({ children }) => <tr className="transition-colors even:bg-muted/25">{children}</tr>,
                hr: () => <hr className="my-8 border-border/60" />,
              }}
            >
              {post.content}
            </ReactMarkdown>
          </div>

          <PostNav currentSlug={post.slug} />

          <RelatedPosts currentSlug={post.slug} />

          <ArticleFooterNote />
        </article>
      </main>
      <Footer />
    </>
  );
}
